Repository ros-visualization/rviz, pull requests merged in 2018-04, with the labels that each got.

#1218 Install help.html
  CMakeLists.txt
Labels: bug

#1158 Taking roi in cameraInfo in consideration when using camera_display plugin
  src/rviz/default_plugin/camera_display.cpp
Labels: bug

#1168 Disable dock widget text eliding
  src/rviz/visualization_frame.cpp
  src/rviz/visualization_frame.h
Labels: enhancement

#1200 Fixed use of LineSpacing, horizontal alignment and AABB calculation in MovableText
  src/rviz/ogre_helpers/movable_text.cpp
Labels: bug

#1229 Ensure robot model has been loaded before processing JointState msg (fix #892)
  src/rviz/default_plugin/effort_display.cpp
Labels: in progress

#1231 change to use non-deprecated header
  src/rviz/default_plugin/point_cloud_common.h
Labels: in progress

#1221 allow classes inheriting from image display access to more state
  src/rviz/default_plugin/image_display.h
Labels: ABI break, enhancement

#1216 Created a new Preferences window, and added PromptSaveOnExit option.
  src/rviz/CMakeLists.txt
  src/rviz/preferences.h
  src/rviz/preferences_dialog.cpp
  src/rviz/preferences_dialog.h
  src/rviz/visualization_frame.cpp
  src/rviz/visualization_frame.h
Labels: ABI break, enhancement

#1233 Show badge of devel job instead of PR job in readme
  README.md
Labels: in progress
