Repository ros-visualization/rviz, pull requests merged in 2018-05, with the labels that each got.

#1230 Indigo backports from kinetic-devel
  CMakeLists.txt
  src/rviz/default_plugin/effort_display.cpp
  src/rviz/default_plugin/markers/triangle_list_marker.cpp
Labels: in progress

#1232 change to use non-deprecated header (#1231)
  src/rviz/default_plugin/point_cloud_common.h
Labels: in progress

#1213 add TF Prefix to effort plugin and fix #892
  src/rviz/default_plugin/effort_display.cpp
  src/rviz/default_plugin/effort_display.h
Labels: ABI break, enhancement

#1237 convert to tinyxml2 to avoid deprecated interfaces in urdf
  CMakeLists.txt
  package.xml
  src/rviz/CMakeLists.txt
  src/rviz/default_plugin/robot_model_display.cpp
  src/rviz/display_factory.cpp
  src/rviz/mesh_loader.cpp
Labels: bug, in progress, needs forward port to ros2

#1239 fix formatting of README.md
  README.md
Labels: enhancement, review

#1196 hiding small wrenches should be optional
  src/rviz/default_plugin/wrench_display.cpp
  src/rviz/default_plugin/wrench_display.h
  src/rviz/default_plugin/wrench_visual.cpp
  src/rviz/default_plugin/wrench_visual.h
Labels: ABI break, enhancement, review

#1236 Deprecate tf for tf2
  src/rviz/default_plugin/axes_display.cpp
  src/rviz/default_plugin/camera_display.cpp
  src/rviz/default_plugin/camera_display.h
  src/rviz/default_plugin/depth_cloud_display.cpp
  src/rviz/default_plugin/depth_cloud_display.h
  src/rviz/default_plugin/effort_display.cpp
  src/rviz/default_plugin/effort_display.h
  src/rviz/default_plugin/grid_cells_display.cpp
  src/rviz/default_plugin/image_display.cpp
  src/rviz/default_plugin/interactive_marker_display.cpp
  src/rviz/default_plugin/interactive_markers/interactive_marker.cpp
  src/rviz/default_plugin/laser_scan_display.cpp
  src/rviz/default_plugin/map_display.cpp
  src/rviz/default_plugin/marker_display.cpp
  src/rviz/default_plugin/markers/arrow_marker.cpp
  src/rviz/default_plugin/markers/marker_base.cpp
  src/rviz/default_plugin/odometry_display.h
  src/rviz/default_plugin/path_display.cpp
  src/rviz/default_plugin/point_cloud_common.cpp
  src/rviz/default_plugin/point_cloud_display.cpp
  src/rviz/default_plugin/robot_model_display.cpp
  src/rviz/default_plugin/tf_display.cpp
  src/rviz/display_context.h
  src/rviz/frame_manager.cpp
  src/rviz/frame_manager.h
  src/rviz/image/image_display_base.cpp
  src/rviz/image/image_display_base.h
  src/rviz/message_filter_display.h
  src/rviz/ogre_helpers/point_cloud.h
  src/rviz/ogre_helpers/render_system.cpp
  src/rviz/ogre_helpers/render_system.h
  src/rviz/properties/tf_frame_property.cpp
  src/rviz/visualization_manager.cpp
  src/rviz/visualization_manager.h
Labels: ABI break, enhancement, review

#1174 add option to disable keyboard focus being set on mouse move
  src/rviz/render_panel.cpp
  src/rviz/render_panel.h
Labels: ABI break, enhancement, needs forward port to ros2, review

#1248 add minimum required pluginlib version
  package.xml
Labels: in progress, review
