Repository ros-visualization/rviz, pull requests merged in 2019-02, with the labels that each got.

#1341 [melodic] Correct xmlDoc.Parse usage.
  src/rviz/mesh_loader.cpp
Labels: in progress, review

#1344 remove support for tf < 1.11.3
  CMakeLists.txt
  src/rviz/default_plugin/effort_display.h
Labels: in progress, review

#1245 Small code cleanup
  src/rviz/ogre_helpers/render_widget.cpp
  src/rviz/render_panel.cpp
Labels: review

#1337 [Windows][melodic] Use c++11 chrono to replace gettimeofday.
  src/test/connect_test.cpp
Labels: changes requested
