Repository ros-visualization/rviz, pull requests merged in 2019-03, with the labels that each got.

#1323 Fixed joint display hierarchy in EffortDisplay
  src/rviz/default_plugin/effort_display.cpp
Labels: need feedback or more info

#1256 Don't hide the toolbar when pressing esc
  src/rviz/visualization_frame.cpp
Labels: review

#1319 Improve color support for themes
  help/help.html
  src/rviz/display.cpp
  src/rviz/failed_display.cpp
  src/rviz/panel_dock_widget.cpp
  src/rviz/properties/property.cpp
  src/rviz/properties/property_tree_with_help.cpp
  src/rviz/properties/status_property.cpp
  src/rviz/properties/status_property.h
  src/rviz/view_controller.cpp
Labels: changes requested

#1255 Add properties for the covariance of the initial pose tool
  src/rviz/default_plugin/tools/initial_pose_tool.cpp
  src/rviz/default_plugin/tools/initial_pose_tool.h
Labels: ABI break, need feedback or more info

#1246 Transform poses in Path message correctly into fixed frame.
  src/rviz/default_plugin/path_display.cpp
  src/test/send_path.py
Labels: changes requested, in progress, review

#1354 replace tinyxml2 ErrorStr() -> ErrorName()
  src/rviz/mesh_loader.cpp
Labels: in progress, review

#1321 Add a shortcut key to the Publish Point tool
  help/help.html
  src/rviz/default_plugin/tools/point_tool.cpp
Labels: needs forward port

#1357 Add ability to set alpha channel value of Axes and TF displays
  src/rviz/default_plugin/axes_display.cpp
  src/rviz/default_plugin/axes_display.h
  src/rviz/default_plugin/tf_display.cpp
  src/rviz/default_plugin/tf_display.h
  src/rviz/ogre_helpers/axes.cpp
  src/rviz/ogre_helpers/axes.h
Labels: ABI break

#1362 Add ability to set Orbit camera field of view
  src/rviz/default_plugin/view_controllers/orbit_view_controller.cpp
  src/rviz/default_plugin/view_controllers/orbit_view_controller.h
Labels: ABI break
